INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Buttermilk Pancakes', 'three large, fluffy hotcakes served with 2 strips of bacon', 'Breakfast', 'Breakfast Classics', 6.50, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('French Toast', 'rich and delicious sourdought french toast, served with 2 strips of bacon or maple sausage', 'Breakfast', 'Breakfast Classics', 7.50, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Belgian Waffle', 'a large, buttery sweet waffle served with french seasonal fruit and whipped cream', 'Breakfast', 'Breakfast Classics', 8.50, true, 20);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('The Junior', 'two eggs any way, 2 strips of bacon or maple sausage links, homefried potatoes', 'Breakfast', 'Breakfast Classics', 7.50, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('The Classic', 'three eggs any way, 4 strips of bacon or maple sausage links, and home fried potatoes', 'Breakfast', 'Breakfast Classics', 9.50, true, 25);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('The Scrambler', 'three eggs scrambled with onions, green peppers, mushrooms, and diced chicken-apple sausage', 'Breakfast', 'Eggs Dishes', 9.50, true, 20);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Pacific NW Hash', 'flaked smoked salmon, bacon, potatoes, onions, topped with poached eggs and sour cream', 'Breakfast', 'Eggs Dishes', 11.00, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Lumberjack Omelet', 'a three-egg omlet with ham, sausage, spinach, mushrooms, cheddar, and home fried potatoes', 'Breakfast', 'Eggs Dishes', 10.25, true, 10);
INSERT INTO menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Mediterranean Omelet', 'two eggs any way, 2 strips of bacon or maple sausage links, homefried potatoes', 'Breakfast', 'Eggs Dishes', 7.50, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Homemade Muffin', 'marionberry, blueberry, or apple cinnamon', 'Breakfast', 'A La Carte', 2.25, true, 20);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Yogurt Granola Fruit Parfait', 'yogurt layered with granola and fresh berries', 'Breakfast', 'A La Carte', 5.00, true, 20);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Home Fried Potatoes', 'Breakfast', 'A La Carte', 2.95, true, 10);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Maple Sausage Links', 'Breakfast', 'A La Carte', 2.50, true, 10);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Bacon (3 strips)', 'Breakfast', 'A La Carte', 2.95, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Tofu Scramble', 'with spinach, mushrooms, green peppers, and cheddar cheese', 'Breakfast', 'Brunch Specials', 9.50, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('French Twist', 'roasted turkey, brie, red onions, and tomato on a warm croissant ', 'Breakfast', 'Brunch Specials', 7.95, true, 20);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Blue Chicken Salad', 'garden greens, apple, grilled chicken, gorgonzola cheese, balsalmic vinaigrette', 'Breakfast', 'Brunch Specials', 10.95, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Chicken Milano', 'auteed in white wine, garlic, herbs & spices, onions, red & green peppers, served on linguine', 'Lunch', 'Chicken', 16.00, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Chicken Dijon', 'grilled & topped with peppers, onions & dijonaise sauce', 'Lunch', 'Chicken', 15.00, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Louisiana Fowl', 'chicken breast with spring onions, tomatoes, hot sauce, cheddar & monterey jack cheeses', 'Lunch', 'Chicken', 14.00, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Burgers', 'the all american low carb plate', 'Lunch', 'Low Carb Lunches', 8.00, true, 20);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Salmon', 'grilled or blackened', 'Lunch', 'Low Carb Lunches', 13.00, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Pork Chops', 'single chop 8 / double chops', 'Lunch', 'Low Carb Lunches', 13.00, true, 10);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price) VALUES ('Pork Chops', 'single jerk chop 8 / double jerk chops', 'Lunch', 'Low Carb Lunches', 14.00);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Chicken Breast', 'grilled', 'Lunch', 'Low Carb Lunches', 12.00, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ("Charlie's One Pound New York Rib Eye", "america's great steak", 'Lunch', 'Steaks & Chops', 24.00, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Cut Pork Chops', 'center cut chops, grilled up fine', 'Lunch', 'Steaks & Chops', 13.00, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Carribean Jerk Pork Chops & Island Apple Sauce', 'marinated with jamaican jerk seasonings with our best island apple sauce', 'Lunch', 'Steaks & Chops', 14.00, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Baby Back Rips', 'served wet or dry with fries and slaw. 1/2 rack 16.00 / full rack', 'Lunch', 'Steaks & Chops', 22.00, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Grilled Salmon Filet', 'in cajun seasoning or topped with dill butter', 'Lunch', "Ocean's Best", 13.00, true, 20);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Stir Fried Shrimp', 'plump shrimp, mushrooms, broccoli, green & red peppers, stir fried in teriyaki sauce, served with salad', 'Lunch', "Ocean's Best", 12.00, true, 25);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Fried Shrimp Tempura', 'lightly battered & deep fried to a golden delicious crunch', 'Lunch', "Ocean's Best", 13.00, true, 25);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Whiskey King', 'maple bourbon glazed cipollini, rogue bleu cheese, applewood bacon, foie gras', 'Dinner', 'Burgers', 26.00, true, 20);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Village Burger', 'sesame roll, tomato, boston bibb, house made thousand island', 'Dinner', 'Burgers', 13.00, true, 15);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Veggie Burger', 'black bean & lentil, guacamole, pickled red cabbage', 'Dinner', 'Burgers', 12.00, true, 25);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('BBQ Pork Sammy', 'pulled pork shoulder, whiskey bbq, cole slaw, fried pickle', 'Dinner', 'Entrees', 12.00, true, 25);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Chickenn Sandwich', 'long hots peppers, mushrooms, sharp provolone', 'Dinner', 'Entrees', 12.00, true, 30);
INSERT INTO Menus (menu_name, menu_description, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Kentucky Hot Brown', 'sliced turkey, toasted brioche, smoked baconm mornay sauce', 'Dinner', 'Entrees', 12.00, true, 20);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Seasonal Pie', 'Dinner', 'Desserts', 9.00, true, 30);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Chocolate Lava Cake', 'Dinner', 'Desserts', 8.50, true, 30);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Fried Icecream', 'Dinner', 'Desserts', 9.25, true, 30);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('New Belgium Fat Tire', 'Drinks', 'Cold Beer', 3.75, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Gigantic IPA', 'Drinks', 'Cold Beer', 4.50, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Brooklyn Brewery Lager', 'Drinks', 'Cold Beer', 4.50, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Pina Colada', 'Drinks', 'Mixed Drinks', 3.75, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Blueberry Twist', 'Drinks', 'Mixed Drinks', 4.50, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Bloody Mary', 'Drinks', 'Mixed Drinks', 4.50, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Margarita', 'Drinks', 'Mixed Drinks', 4.00, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Cabernet Franc', 'Drinks', 'Red Wine', 5.75, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Nebbiolo', 'Drinks', 'Red Wine', 4.50, true, 50);
INSERT INTO Menus (menu_name, menu_category, menu_subcategory, menu_price, menu_catering_availability, menu_catering_min_order) VALUES ('Grenache', 'Drinks', 'Red Wine', 4.00, true, 50);

INSERT INTO Tables (table_name, table_people) VALUES ('101', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('102', 8);
INSERT INTO Tables (table_name, table_people) VALUES ('103', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('104', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('105', 8);
INSERT INTO Tables (table_name, table_people) VALUES ('106', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('107', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('108', 8);
INSERT INTO Tables (table_name, table_people) VALUES ('109', 4);
INSERT INTO Tables (table_name, table_people) VALUES ('110', 4);
INSERT INTO Tables (table_name, table_people) VALUES ('111', 4);
INSERT INTO Tables (table_name, table_people) VALUES ('201', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('202', 8);
INSERT INTO Tables (table_name, table_people) VALUES ('203', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('204', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('205', 8);
INSERT INTO Tables (table_name, table_people) VALUES ('206', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('207', 6);
INSERT INTO Tables (table_name, table_people) VALUES ('208', 8);
INSERT INTO Tables (table_name, table_people) VALUES ('209', 4);
INSERT INTO Tables (table_name, table_people) VALUES ('210', 4);
INSERT INTO Tables (table_name, table_people) VALUES ('211', 4);

INSERT INTO Customers (customer_name, customer_username, customer_password, customer_birthday, customer_email, customer_phone) VALUES ('Min', 'min', '123', '01/01/1111', 'min@gmail.com', '111-111-1111');
INSERT INTO Customers (customer_name, customer_username, customer_password, customer_birthday, customer_email, customer_phone) VALUES ('Nicholas', 'nicholas', '123', '01/01/1111', 'nicholas@gmail.com', '111-111-1111');
INSERT INTO Customers (customer_name, customer_username, customer_password, customer_birthday, customer_email, customer_phone) VALUES ('Rebeacca', 'rebeacca', '123', '01/01/1111', 'rebeacca@gmail.com', '111-111-1111');

INSERT INTO Information (information_date, information_opened) VALUES ('MON', false);
INSERT INTO Information (information_date, information_opened, information_open_hour, information_close_hour) VALUES ('TUE', true, '9:00:00', '22:00:00');
INSERT INTO Information (information_date, information_opened, information_open_hour, information_close_hour) VALUES ('WED', true, '9:00:00', '22:00:00');
INSERT INTO Information (information_date, information_opened, information_open_hour, information_close_hour) VALUES ('THUR', true, '9:00:00', '22:00:00');
INSERT INTO Information (information_date, information_opened, information_open_hour, information_close_hour) VALUES ('FRI', true, '9:00:00', '24:00:00');
INSERT INTO Information (information_date, information_opened, information_open_hour, information_close_hour) VALUES ('SAT', true, '10:00:00', '24:00:00');
INSERT INTO Information (information_date, information_opened, information_open_hour, information_close_hour) VALUES ('SUN', true, '10:00:00', '21:00:00');
